name: on-push

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - run: gh cache delete -a
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
